-- MySQL Script generated by MySQL Workbench
-- Mon Jan  2 13:27:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testEnee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testEnee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testEnee` DEFAULT CHARACTER SET utf8 ;
USE `testEnee` ;

-- -----------------------------------------------------
-- Table `testEnee`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testEnee`.`user` ;

CREATE TABLE IF NOT EXISTS `testEnee`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testEnee`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testEnee`.`branch` ;

CREATE TABLE IF NOT EXISTS `testEnee`.`branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `administrator_name` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `order_numbers` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  INDEX `fk_branch_user_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_branch_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `testEnee`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testEnee`.`change_log_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testEnee`.`change_log_type` ;

CREATE TABLE IF NOT EXISTS `testEnee`.`change_log_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testEnee`.`change_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testEnee`.`change_log` ;

CREATE TABLE IF NOT EXISTS `testEnee`.`change_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `change_log_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_change_log_user1_idx` (`user_id` ASC) ,
  INDEX `fk_change_log_branch1_idx` (`branch_id` ASC) ,
  INDEX `fk_change_log_change_log_type1_idx` (`change_log_type_id` ASC) ,
  CONSTRAINT `fk_change_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testEnee`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_change_log_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `testEnee`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_change_log_change_log_type1`
    FOREIGN KEY (`change_log_type_id`)
    REFERENCES `testEnee`.`change_log_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
